---
abstract: 'A simple, sane and efficient file slurper'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Slurper
provides:
  File::Slurper:
    file: lib/File/Slurper.pm
    version: '0.002'
requires:
  Carp: '0'
  Exporter: '5.57'
  File::Spec::Functions: '0'
  PerlIO::utf8_strict: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-Slurper
  repository: git://github.com/Leont/file-slurp-sane.git
version: '0.002'
